### PR TITLE
Lims 3423/4297

### PR DESCRIPTION
**Pull request by dianaeldemerdash**

### CODE REVIEW

**Comment by 0xIslamTaha** [comment]
The implementation of this test case is wrong, Please, Check the implementation of "test014_update_order_material_type" and do like it.

**Comment by dianaeldemerdash** [comment]
@0xIslamTaha  what is wrong in the implementation I can't use the same method in update the material type because update the article is different

**Comment by 0xIslamTaha** [comment]
@dianaeldemerdash Logic is wrong. for sure I'm not asking to copy_paste the code, I'm talking about the logic of the test case

**Comment by dianaeldemerdash** [comment]
@0xIslamTaha we should create record first as we agreed because I cant work on any record same as update the material type because I want when I update the article the materiel type not changed

**Comment by dianaeldemerdash** [comment]
@0xIslamTaha  so please clarify because I don't understand or you can write specific comments to understand the logic is different totally in update the article & in update the material type

**Comment by 0xIslamTaha** [comment]
please check "test014_update_order_material_type" code as we already made this conversation when u implemented it and I fixed the logic of it then send my commit to you.

**Comment by 0xIslamTaha** [comment]
@dianaeldemerdash as we agreed in the call, you are going to create a method to get complete test plan and active article with specific material type and use it in the test case.

**Comment by dianaeldemerdash** [comment]
@0xIslamTaha yes I started in it but not finish yet this was on Monday and yesterday I was in a vacation

**Comment by 0xIslamTaha** [comment]
as we discussed, This PR gonna close as it needs to re-implement

**Pull request closed without merging**
